src/Entity/Event.php
<?php

namespace App\Entity;

use App\Repository\EventRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Serializer\Annotation\Groups;

#[UniqueEntity(fields: ['title'], message: 'There is already an event with this title')]
#[ORM\Entity(repositoryClass: EventRepository::class)]
class Event
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("events")]
    private ?int $id = null;

    #[ORM\Column(length: 255, unique: true)]
    #[Groups("events")]
    #[Assert\NotBlank(message: 'Please enter a title.')]
    #[Assert\Length(max: 20, maxMessage: "The Field Title cannot cannot contain more than {{20}} caracters")]
    #[Assert\Regex(pattern: "/^[a-zA-Z0-9 ]*$/", message: "The Field Title can only contain letters and numbers")]
    private ?string $title;

    #[ORM\Column(length: 255)]
    #[Groups("events")]
    #[Assert\NotBlank(message: 'Please enter a description.')]
    #[Assert\Length(max: 100, maxMessage: "The Field Desciption cannot cannot contain more than {{20}} caracters")]
    #[Assert\Regex(pattern: "/^[a-zA-Z0-9 ]*$/", message: "The Field Title can only contain letters and numbers")]
    private ?string $description = null;

    #[ORM\Column]
    #[Groups("events")]
    #[Assert\GreaterThanOrEqual(value: 0)]
    private ?int $nb_placeMax = null;

    #[ORM\Column(type: 'date', nullable: false)]
    #[Groups("events")]
    #[Assert\NotBlank(message: 'Please enter a Date.')]
    #[Assert\GreaterThanOrEqual('today', message: 'The start date must be a date that is later than the current date.')]
    private ?\DateTimeInterface $date_beg;

    #[ORM\Column(type: 'date', nullable: false)]
    #[Groups("events")]
    #[Assert\NotBlank(message: 'Please enter a Date.')]
    #[Assert\GreaterThanOrEqual(propertyPath: 'date_beg', message: 'The end date must be a date that is later than the start date.')]
    private ?\DateTimeInterface $date_end;

    // public function getToday(): ?\DateTimeInterface
    // {
    //     return new \DateTime();
    // }




    #[ORM\Column(length: 255)]
    #[Groups("events")]
    #[Assert\NotBlank(message: "Image is required")]
    private ?string $image = null;

    #[ORM\ManyToOne(inversedBy: 'events')]
    private ?EventCategorie $categorie = null;



    #[ORM\OneToMany(mappedBy: 'id_event', targetEntity: Reservation::class, cascade: ['remove'])]
    private Collection $reservations;




    public function __construct()
    {

        $this->id_event = new ArrayCollection();
        $this->reservations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getNbPlaceMax(): ?int
    {
        return $this->nb_placeMax;
    }

    public function setNbPlaceMax(int $nb_placeMax): self
    {
        $this->nb_placeMax = $nb_placeMax;

        return $this;
    }

    public function getDateBeg(): ?\DateTimeInterface
    {
        return $this->date_beg;
    }

    public function setDateBeg(\DateTimeInterface $date_beg): self
    {
        $this->date_beg = $date_beg;

        return $this;
    }

    public function getDateEnd(): ?\DateTimeInterface
    {
        return $this->date_end;
    }

    public function setDateEnd(\DateTimeInterface $date_end): self
    {
        $this->date_end = $date_end;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    public function getCategorie(): ?EventCategorie
    {
        return $this->categorie;
    }

    public function setCategorie(?EventCategorie $categorie): self
    {
        $this->categorie = $categorie;

        return $this;
    }



    /**
     * @return Collection<int, Reservation>
     */
    public function getIdEvent(): Collection
    {
        return $this->id_event;
    }

    public function addIdEvent(Reservation $idEvent): self
    {
        if (!$this->id_event->contains($idEvent)) {
            $this->id_event->add($idEvent);
            $idEvent->setIdEvent($this);
        }

        return $this;
    }

    public function removeIdEvent(Reservation $idEvent): self
    {
        if ($this->id_event->removeElement($idEvent)) {
            // set the owning side to null (unless already changed)
            if ($idEvent->getIdEvent() === $this) {
                $idEvent->setIdEvent(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Reservation>
     */
    public function getReservations(): Collection
    {
        return $this->reservations;
    }

    public function addReservation(Reservation $reservation): self
    {
        if (!$this->reservations->contains($reservation)) {
            $this->reservations->add($reservation);
            $reservation->setIdEvent($this);
        }

        return $this;
    }

    public function removeReservation(Reservation $reservation): self
    {
        if ($this->reservations->removeElement($reservation)) {
            // set the owning side to null (unless already changed)
            if ($reservation->getIdEvent() === $this) {
                $reservation->setIdEvent(null);
            }
        }

        return $this;
    }
}

src/Controller/EventController.php
<?php

namespace App\Controller;
use App\Form\SearchEventFormType;
use App\Repository\EventRepository;
use App\Form\EventType;
use App\Entity\Event;
use App\Entity\EventCategorie;
use App\Repository\ReservationRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use App\Entity\User;
use Doctrine\Persistence\ManagerRegistry as PersistenceManagerRegistry;
use Swift_Mailer;
use Swift_Message;
use Swift_SmtpTransport;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use App\Entity\Reservation;


class EventController extends AbstractController
{   
    #[Route('/event', name: 'app_event')]
    public function index(Request $request, EventRepository $eventRepository): Response
    {
        $form = $this->createForm(SearchEventFormType::class);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $ev = $eventRepository->findSearch($data['nbPlaceMax'], $data['categorie']);
        } else {
            $ev = $eventRepository->findAll();
        }
    
        return $this->render('event/index.html.twig', [
            'ev' => $ev,
            'form' => $form->createView(),
        ]);
    }
    
    
    #[Route('/event/{id}', name: 'app_eventUser')]
    public function indexUser(int $id,Request $request, EventRepository $eventRepository,EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(SearchEventFormType::class);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $data = $form->getData();
            $ev = $eventRepository->findSearch($data['nbPlaceMax'], $data['categorie']);
        } else {
            $ev = $eventRepository->findAll();
        }
       

    
        return $this->render('event/indexUser.html.twig', [
            'ev' => $ev,
            'form' => $form->createView(),
        ]);
    }

    
    

    


    // #[Route('/readEvent', name: 'app_readEvent')]
    // public function readEvent(EventRepository $eventRepository): Response
    // {
    //     //Utiliser findAll()
    //     $events = $eventRepository->findAll();
    //     return $this->render('event/AffichageEvent.html.twig', [
    //         'event' => $events,
    //     ]);
    // }
    
    // #[Route('/detailEvent', name: 'app_detailEvent')]
    // public function detailEvent(EventRepository $eventRepository): Response
    // {
        
    //     //Utiliser findAll()
    //     $events = $eventRepository->findAll();
    //     return $this->render('event/detailsEvent.html.twig', [
    //         'event' => $events,
    //     ]);
    // }

    #[Route('/detailEvent/{id}', name: 'app_detailEvent', methods: ["GET", "POST"] )]
    public function show($id, EventRepository $rep, Request $request): Response
    {
        //Utiliser find by id
        $event = $rep->find($id);
        return $this->render('event/detailsEvent.html.twig', [
            'event' => $event,
        ]);
    }

    #[Route('/detailEventUser/{id}', name: 'app_detailEventUser', methods: ["GET", "POST"] )]
    public function showUser($id, EventRepository $rep, Request $request): Response
    {
        //Utiliser find by id
        $event = $rep->find($id);
        $eventId = $event->getId();
        return $this->render('event/detailsEventUser.html.twig', [
            'event' => $event,
            'eventId' => $eventId
        ]);
    }




    #[Route('/deleteEvent/{id}', name: 'app_deleteEvent')]
    public function deleteEvent($id, EventRepository $rep, ReservationRepository $reservationRep, ManagerRegistry $doctrine, SessionInterface $session,Swift_Mailer $mailer): Response
    {
        //récupérer la classe à supprimer
        $event=$rep->find($id);
        if (!$event) {
            throw $this->createNotFoundException('Event not found for id '.$id);
        }
        // Récupérer toutes les réservations de cet événement
        $reservations = $reservationRep->findBy(['id_event' => $event]);
    
        // Supprimer l'événement
        $em=$doctrine->getManager();
        $em->remove($event);
    
       
       // Envoyer une notification à chaque utilisateur ayant réservé des places dans cet événement
       $message = ''; // initialiser la variable message
foreach ($reservations as $reservation) {
    $user = $reservation->getIdParticipant();
    $eventTitle = $event->getTitle();
    $message = 'The event "' . $eventTitle . '" has been cancelled.';
    $session->getFlashBag()->add('danger', $message);
    $this->emailAnnulation($user, $eventTitle, $mailer);

}
    
        // Enregistrer les modifications dans la base de données
        $em->flush();
    
        return $this->redirectToRoute('app_event');
    }
    
    #[Route('/addEvent', name: 'app_addEvent')]
    public function addEvent(ManagerRegistry $doctrine,
    Request $request)
{
    $event= new Event();
$form=$this->createForm(EventType::class,$event);
                   $form->handleRequest($request);
                   if($form->isSubmitted()&& $form->isValid()){
                    $file = $form['image']->getData();
            $fileName = $file->getClientOriginalName();
            $file->move("C:/xampp/htdocs/img", $fileName);
            $event->setImage($fileName);
                    //Action d'ajout
                       $em =$doctrine->getManager() ;
                       $em->persist($event);
                       $em->flush();
            return $this->redirectToRoute("app_event");
        }
    return $this->renderForm("event/createEvent.html.twig",
                       array("form"=>$form));
                   }

                   #[Route('/updateEvent/{id}', name: 'app_updateEvent')]
                   public function updateEvent($id, EventRepository $eventRepository, ManagerRegistry $doctrine, Request $request,
                   EntityManagerInterface $entityManager,Swift_Mailer $mailer, ReservationRepository $reservationRep)
                   {
                       //récupérer la classe à modifier
                       $event = $eventRepository->find($id);
                       $form = $this->createForm(EventType::class,$event);
                       $form->handleRequest($request);
                       if ($form->isSubmitted() && $form->isValid()) {
                        $file = $form['image']->getData();
                        $fileName = $file->getClientOriginalName();
                        $file->move("C:/xampp/htdocs/img", $fileName);
                        $event->setImage($fileName);
                        $entityManager->flush();

 // Récupérer toutes les réservations de cet événement
        $reservations = $reservationRep->findBy(['id_event' => $event]);
    
                         // Envoyer une notification à chaque utilisateur ayant réservé des places dans cet événement
                        foreach ($reservations as $reservation) {
                              $user = $reservation->getIdParticipant();
                             $eventTitle = $event->getTitle();
                     }
                            
                            $this->emailUpdate($user, $eventTitle, $mailer);
                           return $this->redirectToRoute("app_event");
                       }
                       return $this->renderForm("event/updateEvent.html.twig", array("form"=>$form));
                   }   
                   
                   public function emailAnnulation ($user,$eventTitle, $mailer){
                    // Create a new SMTP transport with the desired configuration
                    $dsn = getenv('MAILER_DSN');
                    $transport = new Swift_SmtpTransport('smtp.gmail.com', 587, 'tls');
                    $transport->setUsername('meriam123.hammi@gmail.com');
                    $transport->setPassword('wnevuhcvabtqhhiz');
                
                    $mailer = new Swift_Mailer($transport);
                
                    //BUNDLE MAILER
                    $message = (new Swift_Message('Annulaion evenement'))
                        ->setFrom('meriam123.hammi@gmail.com')
                        ->setTo($user->getEmail())
                        ->setBody(" Bonjour,\n Nous vous informons que l'événement \"$eventTitle\"pour lequel vous avez réservé des places a été annulé.");
                
                    //send mail
                    $mailer->send($message);
                }
                public function emailUpdate ($user,$eventTitle, $mailer){
                    // Create a new SMTP transport with the desired configuration
                    $dsn = getenv('MAILER_DSN');
                    $transport = new Swift_SmtpTransport('smtp.gmail.com', 587, 'tls');
                    $transport->setUsername('meriam123.hammi@gmail.com');
                    $transport->setPassword('wnevuhcvabtqhhiz');
                
                    $mailer = new Swift_Mailer($transport);
                
                    //BUNDLE MAILER
                    $message = (new Swift_Message('Modification evenement'))
                        ->setFrom('meriam123.hammi@gmail.com')
                        ->setTo($user->getEmail())
                        ->setBody(" Bonjour,\n Nous vous informons que l'événement \"$eventTitle\"pour lequel vous avez réservé des places a été modifié, veuillez consulter dans notre site web.");
                
                    //send mail
                    $mailer->send($message);
                }
}

templates/event/AffichageEvent.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
        {% for e in event  %}
            <tr>
                <th>Id</th>
                <td>{{ e.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ e.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ e.description }}</td>
            </tr>
             <tr>
                <th>Number of places</th>
                <td>{{ e.nbPlacemax }}</td>
            </tr>
             <tr>
                <th>Date begin</th>
                <td>{{ e.dateBeg |date('Y-m-d')}}</td>
            </tr>
             <tr>
                <th>Date end</th>
                <td>{{ e.dateEnd|date('Y-m-d') }}</td>
            </tr>
            
            <tr>
                <th>Url</th>
                <td>{{ e.url }}</td>
            </tr>
            <tr>
                {# <th>Category</th>
                <td>{{ e.categorie.nomcategorie }}</td> #}
                <th>Category</th>
                {% if e.categorieEvent is not null %}
                    <td>{{ e.categorieEvent.nomcategorie }}</td>
                {% else %}
                    <td>No category</td>
                {% endif %}
            </tr>
             
        

    <a href="{{ path('app_event') }}">back to list</a>

    {# <a href="{{ path('app_updateEvent', {'id': e.id}) }}">edit</a> #}
    
 <td><form action="{{path('app_updateEvent',{'id':e.id}) }}">
                <button>Update</button></form></td>
   <td><form action="{{path('app_deleteEvent',{'id':e.id}) }}">
            <button>Delete</button></form></td>
              {% endfor %}
              </tbody>
       
    </table>
{% endblock %}

templates/event/details.html.twig
{% extends 'base.html.twig' %}

{% block body %}
  <div class="container my-5">
    <div class="row">
      <div class="col">
        <h1>{{ event.title }}</h1>
        <p>{{ event.description }}</p>
        <p>Nombre de places disponibles : {{ event.nbPlacemax }}</p>
        <p>Début de l'événement : {{ event.dateBeg|date('d/m/Y H:i') }}</p>
        <p>Fin de l'événement : {{ event.dateEnd|date('d/m/Y H:i') }}</p>
        <img src="{{ event.url }}" alt="{{ event.title }}" class="img-fluid">
        <p>Catégorie : {{ event.categorieEvent.nomCategorieEvent }}</p>
      </div>
    </div>
  </div>
{% endblock %}

templates/event/eventFeed.html.twig
{% extends 'base.html.twig' %}




{% block body %}
 <section class="page-header" style="background-image: url({{asset('images/backgrounds/page-header-bg-1-1.jpg')}});">
            <div class="container">
                <h2>Events</h2>
            </div><!-- /.container -->
        </section><!-- /.page-header -->
  
        <section class="event-details">
            <div class="container">
                <div class="event-details__top">
                  <div class="block-title text-left">
                        <p>Events  </p>
                        <h3>Explore <br> Our events</h3>
                    </div>
    
    {{ form_start(form) }}
        {# {{ form_row(form.dateBeg) }}
        {{ form_row(form.dateEnd) }} #}
        {{ form_row(form.nbPlaceMax) }}
        {{ form_row(form.categorie, {'empty_data': null}) }}
        {{ form_row(form.Search) }}
    {{ form_end(form) }}

    <div class="row">
        {% for e in ev %}
        {% if (form.Search.vars.value is empty or e.title matches '/^.*' ~ form.Search.vars.value ~ '.*$/i') and
                  (form.nbPlaceMax.vars.value is empty or e.nbPlaceMax <= form.nbPlaceMax.vars.value) and
                  (form.categorie.vars.value is empty or e.categorie.id == form.categorie.vars.value) %}
            <div class="col-lg-4 col-md-6 filter-item masonary-item {{e.categorie.nom}}">
                <div class="collection-grid__single">
                    <div class="collection-grid__image">
                        <img src="http://localhost/img/{{e.image}}" width="363" height="363" alt="">
                    </div><!-- /.collection-grid__image -->
                    <div class="collection-grid__content">
                        <h3><a href="{{ path('app_detailEventUser', {'id': e.id}) }}">{{e.title}}</a></h3>
                       <strong>Description:</strong> <p>{{e.description}}</p>
<strong>Nombre de places maximum:</strong> <p>{{e.nbPlaceMax}}</p>
<strong>Date de début:</strong> <p>{{e.dateBeg |date('Y-m-d')}}</p>
<strong>Date de fin:</strong> <p>{{e.dateEnd |date('Y-m-d')}}</p>

          </div><!-- /.collection-grid__content -->
                </div><!-- /.collection-grid__single -->
            </div><!-- /.col-lg-4 col-md-6 filter-item masonary-item -->
  {% endif %}
        {% endfor %}
         </div><!-- /.row -->
        </div><!-- /.row -->
            </div><!-- /.container -->
             
        </section><!-- /.event-details -->
{% endblock %}
  
           

templates/event/index.html.twig
{% extends 'dashboard-base.html.twig' %}


{% block title %}Event{% endblock %}
{% block nav %}
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Gestion events</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{{ path('app_addEvent')}}" class="dropdown-item">create event</a>
                            <a href="{{ path('app_addCategorie')}}" class="dropdown-item">create type</a>
                            <a href="{{ path('app_event_categorie')}}" class="dropdown-item">list type</a>
                                    <a href="{{ path('app_reservation')}}" class="dropdown-item">list reservation</a>

                        </div>
                    </div>
                    
                </div>
            </nav>
        </div>

        <!-- Sidebar End -->
{% endblock %}
{% block body %}
    <h1>Event index</h1>
    
    {{ form_start(form) }}
        {# {{ form_row(form.dateBeg) }}
        {{ form_row(form.dateEnd) }} #}
        {{ form_row(form.nbPlaceMax) }}
        {{ form_row(form.categorie, {'empty_data': null}) }}
        {{ form_row(form.Search) }}
    {{ form_end(form) }}

    <div class="row">
        {% for e in ev %}
        {% if (form.Search.vars.value is empty or e.title matches '/^.*' ~ form.Search.vars.value ~ '.*$/i') and
                  (form.nbPlaceMax.vars.value is empty or e.nbPlaceMax <= form.nbPlaceMax.vars.value) and
                  (form.categorie.vars.value is empty or e.categorie.id == form.categorie.vars.value) %}
            <div class="col-lg-4 col-md-6 filter-item masonary-item {{e.categorie.nom}}">
                <div class="collection-grid__single">
                    <div class="collection-grid__image">
                        <img src="http://localhost/img/{{e.image}}" width="363" height="363" alt="">
                    </div><!-- /.collection-grid__image -->
                    <div class="collection-grid__content">
                        <h3><a href="{{ path('app_detailEvent', {'id': e.id}) }}">{{e.title}}</a></h3>
                       <strong>Description:</strong> <p>{{e.description}}</p>
<strong>Nombre de places maximum:</strong> <p>{{e.nbPlaceMax}}</p>
<strong>Date de début:</strong> <p>{{e.dateBeg |date('Y-m-d')}}</p>
<strong>Date de fin:</strong> <p>{{e.dateEnd |date('Y-m-d')}}</p>
{% if e.categorie is not null %}
    <strong>Catégorie:</strong> <p>{{ e.categorie.nom }}</p>
{% else %}
    <strong>Catégorie:</strong> <p>No category</p>
{% endif %}

                        <a href="{{ path('app_updateEvent', {'id': e.id}) }}">edit</a>
                        <a href="{{ path('app_deleteEvent', {'id': e.id}) }}">delete</a>
                        {# <a href="{{ path('app_detailEvent', {'id': e.id}) }}">details</a> #}
                    </div><!-- /.collection-grid__content -->
                </div><!-- /.collection-grid__single -->
            </div><!-- /.col-lg-4 col-md-6 filter-item masonary-item -->
            
            {% if loop.index is divisible by(3) %}
                </div><div class="row">
            {% endif %}
             {% endif %}
        {% endfor %}
    </div><!-- /.row -->

    <a href="{{ path('app_addEvent') }}">Create new</a>
    <a href="{{ path('app_event_categorie') }}">Categories</a>
    
{% endblock %}
  
           

templates/event/indexUser.html.twig
{% extends 'base.html.twig' %}


{% block title %}Event{% endblock %}

{% block body %}
  <section class="page-header" style="background-image: url({{asset('images/backgrounds/page-header-bg-1-1.jpg')}});">
            <div class="container ">
                <h2>Events</h2>
            </div><!-- /.container -->
        </section><!-- /.page-header -->
  
        <section class="event-details">
            <div class="container">
                <div class="event-details__top">
                  <div class="block-title text-left mb-4">
                        <p>Events  </p>
                        <h3>Explore <br> Our events</h3>
                    </div>
    <a href="{{ path('app_reservationUser') }}" class="thm-btn contact-one__btn float-right">Mes réservations</a>

    {{ form_start(form) }}
        {{ form_row(form.nbPlaceMax) }}
        {{ form_row(form.categorie, {'empty_data': null}) }}
        {{ form_row(form.Search,{'attr':{'class':'thm-btn contact-one__btn mb-4'}}) }}
    {{ form_end(form) }}

    <div class="row">
        {% for e in ev %}
         {% if (form.Search.vars.value is empty or e.title matches '/^.*' ~ form.Search.vars.value ~ '.*$/i') and
                  (form.nbPlaceMax.vars.value is empty or e.nbPlaceMax <= form.nbPlaceMax.vars.value) and
                  (form.categorie.vars.value is empty or e.categorie.id == form.categorie.vars.value) %}
            <div class="col-lg-4 col-md-6 filter-item masonary-item {{e.categorie.nom}}">
                <div class="collection-grid__single">
                    <div class="collection-grid__image">

                        <img src="http://localhost/img/{{e.image}}" width="350" height="350" alt="">
                    </div><!-- /.collection-grid__image -->
                    <div class="collection-grid__content">
                    
                        <h3><a href="{{ path('app_detailEventUser', {'id': e.id}) }}">{{e.title}}</a></h3>
                       <strong>Description:</strong> <p>{{e.description}}</p>
<strong>Nombre de places maximum:</strong> <p>{{e.nbPlaceMax}}</p>
<strong>Date de début:</strong> <p>{{e.dateBeg |date('Y-m-d')}}</p>
<strong>Date de fin:</strong> <p>{{e.dateEnd |date('Y-m-d')}}</p>
{% if e.categorie is not null %}
    <strong>Catégorie:</strong> <p>{{ e.categorie.nom }}</p>
{% else %}
    <strong>Catégorie:</strong> <p>No category</p>
{% endif %} {% if app.user %}
{% if e.nbPlaceMax == 0 %}
              <button class="  thm-btn contact-one__btn btn-danger " href="#" disabled>Event Full</button>
              {% else %}
                            <a class="thm-btn contact-one__btn " href="{{ path('app_addReservation', {'id': e.id}) }}">Reserver</a>

               {% endif %}
 {% endif %}
                       
                    </div><!-- /.collection-grid__content -->
                </div><!-- /.collection-grid__single -->
            </div><!-- /.col-lg-4 col-md-6 filter-item masonary-item -->
            
            {% if loop.index is divisible by(3) %}
                </div><div class="row">
            {% endif %}
            {% endif %}
            
        {% endfor %}
        
    </div><!-- /.row -->
   </div><!-- /.row -->
        </div><!-- /.row -->
            </div><!-- /.container -->
             
        </section><!-- /.event-details -->
    
    
    
       <section class="cta-one" style="background-image: url({{asset('images/shapes/cta-bg-1-1.jpg')}});">
            <div class="container text-center">
                <h3>More Than 1250 Exhibits!</h3>
                <p>Every day more exhibits arrive in our museum. Do not <br> wait and buy a ticket now.</p>
                <div class="cta-one__btn-block">
                    <a href="#" class="thm-btn cta-one__btn-one">Become A Member</a><!-- /.thm-btn cta-one__btn-one -->
                    <a href="#" class="thm-btn cta-one__btn-two">Buy Online</a><!-- /.thm-btn cta-one__btn-two -->
                </div><!-- /.cta-one__btn-block -->
            </div><!-- /.container -->
        </section><!-- /.cta-one -->
{% endblock %}
  
           

templates/event/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Event{% endblock %}

{% block body %}
    <h1>Event</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ event.id }}</td>
            </tr>
            <tr>
                <th>Title</th>
                <td>{{ event.title }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ event.description }}</td>
            </tr>
             <tr>
                <th>Number of places</th>
                <td>{{ event.nb_placeMax }}</td>
            </tr>
             <tr>
                <th>Date begin</th>
                <td>{{ event.date_beg }}</td>
            </tr>
             <tr>
                <th>Date end</th>
                <td>{{ event.date_end }}</td>
            </tr>
            
            <tr>
                <th>Url</th>
                <td>{{ event.url }}</td>
            </tr>
            <tr>
                <th>Category</th>
                <td>{{ event.categorie }}</td>
            </tr>
             
        </tbody>
    </table>

    <a href="{{ path('app_event_index') }}">back to list</a>

    <a href="{{ path('app_event_edit', {'id': event.id}) }}">edit</a>

    {{ include('event/_delete_form.html.twig') }}
{% endblock %}