src/Entity/Reservation.php
<?php

namespace App\Entity;

use App\Repository\ReservationRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: ReservationRepository::class)]
class Reservation
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups("reservations")]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]
    private ?Event $id_event = null;

    #[ORM\ManyToOne(inversedBy: 'reservations')]

    private ?User $id_participant = null;

    #[ORM\Column]
    #[Groups("reservations")]
    private ?bool $isConfirmed = null;

    #[ORM\Column(type: "integer")]
    #[Assert\Range(min: 1, max: 10)]
    #[Groups("reservations")]
    private ?int $nb_place = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getIdEvent(): ?Event
    {
        return $this->id_event;
    }

    public function setIdEvent(?Event $id_event): self
    {
        $this->id_event = $id_event;

        return $this;
    }

    public function getIdParticipant(): ?User
    {
        return $this->id_participant;
    }

    public function setIdParticipant(?User $id_participant): self
    {
        $this->id_participant = $id_participant;

        return $this;
    }

    public function isIsConfirmed(): ?bool
    {
        return $this->isConfirmed;
    }

    public function setIsConfirmed(bool $isConfirmed): self
    {
        $this->isConfirmed = $isConfirmed;

        return $this;
    }

    public function getNbPlace(): ?int
    {
        return $this->nb_place;
    }

    public function setNbPlace(int $nb_place): self
    {
        $this->nb_place = $nb_place;

        return $this;
    }
}

src/Form/ReservationType.php
<?php

namespace App\Form;

use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use App\Entity\Event;
use App\Entity\User;
use Doctrine\ORM\EntityRepository;
use Symfony\Component\Validator\Constraints\Range;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('isConfirmed')
            ->add('nb_place', IntegerType::class, [
                'attr' => ['min' => 1, 'max' => 10],
                'constraints' => [new Range(['min' => 1, 'max' => 10])]
            ])


            // ->add('id_event',EntityType::class, [
            //     'class'=>Event::class,
            //     'choice_label' => 'title',

            // ])

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,

        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;


use App\Repository\ReservationRepository;
use App\Form\ReservationType;
use App\Entity\Reservation;
use App\Entity\Event;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Doctrine\Persistence\ManagerRegistry;
use App\Repository\EventRepository;
use Doctrine\Persistence\ObjectRepository;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use App\Service\SendMailService;
use App\Service\QRCodeService;
use App\Entity\User;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Endroid\QrCode\QrCode;
use Endroid\QrCode\Writer\PngWriter;
use Swift_Mailer;
use Swift_Message;
use Swift_SmtpTransport;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;




class ReservationController extends AbstractController
{
    #[Route('/admin/reservation', name: 'app_reservation')]
    public function index(EntityManagerInterface $entityManager): Response
    {
        $reservations = $entityManager
            ->getRepository(Reservation::class)
            ->findAll();

        return $this->render('reservation/index.html.twig', [
            'reservations' => $reservations,
        ]);
    }


    #[Route('/user/reservationUser', name: 'app_reservationUser')]
    public function reservationUser(EntityManagerInterface $entityManager)
    {
        $user = $this->getUser();
        if (!$user) {
            throw $this->createNotFoundException('Utilisateur introuvable');
        }
        $reservations = $entityManager->getRepository(Reservation::class)
            ->findBy(['id_participant' => $user]);

        return $this->render('reservation/indexUser.html.twig', [
            'reservations' => $reservations,
        ]);
    }








    #[Route('/admin/deleteReservation/{id}', name: 'app_deleteReservation')]
    public function deleteReservation($id, ReservationRepository $re, ManagerRegistry $doctrine, EventRepository $eventRepository): Response
    {
        //récupérer la classe à supprimer
        $reservations = $re->find($id);
        if (!$reservations) {
            throw $this->createNotFoundException('Reservation not found for id ' . $id);
        }
        //Action de suppression
        //récupérer l'Entitye manager
        $em = $doctrine->getManager();

        // Récupérer l'événement associé à la réservation
        $eventId = $reservations->getIdEvent()->getId();
        $event = $eventRepository->find($eventId);

        // Mettre à jour la capacité de l'événement
        $releasedSeats = $reservations->getNbPlace();
        $this->updateEventCapacity($event, -$releasedSeats);

        $em->remove($reservations);
        //La maj au niveau de la bd
        $em->flush();
        return $this->redirectToRoute("app_reservation");
    }

    // #[Route('/deleteReservationUser/{id}', name: 'app_deleteReservationUser')]
    // public function deleteReservationUser($id, ReservationRepository $re, ManagerRegistry $doctrine): Response
    // {
    //     //récupérer la classe à supprimer
    //     $reservations = $re->find($id);
    //     if (!$reservations) {
    //         throw $this->createNotFoundException('Reservation not found for id '.$id);
    //     }
    //     //Action de suppression
    //     //récupérer l'Entitye manager
    //     $em = $doctrine->getManager();
    //     $em->remove($reservations);
    //     //La maj au niveau de la bd
    //     $em->flush();
    //     return $this->redirectToRoute("app_reservationUser");
    // }
    #[Route('/user/deleteReservationUser/{id}', name: 'app_deleteReservationUser')]
    public function deleteReservationUser(
        $id,
        ReservationRepository $re,
        ManagerRegistry $doctrine,
        EventRepository $eventRepository,
        SessionInterface $session
    ): Response {
        //récupérer la classe à supprimer
        $reservations = $re->find($id);
        if (!$reservations) {
            throw $this->createNotFoundException('Reservation not found for id ' . $id);
        }

        // vérifier si la date de début de l'événement est dans plus de 24h
        $eventDate = $reservations->getIdEvent()->getDateBeg();
        $now = new \DateTime();
        $diff = $now->diff($eventDate);
        if ($diff->days < 1) {
            $session->getFlashBag()->add('error', 'You cannot delete your reservation less than 1 day before the event');
            return $this->redirectToRoute('app_reservationUser');
        }

        //Action de suppression
        //récupérer l'Entitye manager
        $em = $doctrine->getManager();

        // Récupérer l'événement associé à la réservation
        $eventId = $reservations->getIdEvent()->getId();
        $event = $eventRepository->find($eventId);

        // Mettre à jour la capacité de l'événement
        $releasedSeats = $reservations->getNbPlace();
        $this->updateEventCapacity($event, -$releasedSeats);

        $em->remove($reservations);
        //La maj au niveau de la bd
        $em->flush();
        return $this->redirectToRoute("app_reservationUser");
    }


    #[Route('/user/addReservation/{id}', name: 'app_addReservation')]
    public function addReservation(
        ManagerRegistry $doctrine,
        Request $request,
        EventRepository $eventRepository,
        SessionInterface $session,
        SendMailService $emailService,
        $id,
        QrcodeService $qrcodeService,
        Swift_mailer $mailer
    ): Response {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);


        $em = $this->getDoctrine()->getManager();

        $user = $this->getUser();
        // in index function
        // $eventId = 39; // replace with the ID of the desired event

        $eventRepository = $em->getRepository(Event::class);
        $event = $eventRepository->find($id);

        $qrcodeDataUri = $qrcodeService->qrcode($event->getTitle(), $event->getId(), $event->getDescription(), $event->getdateBeg(), $event->getdateEnd());



        $form->handleRequest($request);
        $userRepository = $doctrine->getRepository(User::class);



        if ($form->isSubmitted() && $form->isValid()) {
            // $eventId = $reservation->getIdEvent()->getId();
            $event = $eventRepository->find($id);
            $reservation = $form->getData();

            $reservedSeats = $reservation->getNbPlace();
            $availableSeats = $event->getNbPlaceMax();
            $reservation->setIdEvent($event);
            $reservation->setIdParticipant($user);

            if ($availableSeats === 0) {
                $this->addFlash('error', 'L\'événement est complet !');
                return $this->redirectToRoute('app_reservationUser');
            }

            if ($reservedSeats > $availableSeats) {
                $this->addFlash('error', 'Nombre de places indisponible !');
                return $this->redirectToRoute('app_createReservation');
            }

            $em = $doctrine->getManager();

            $this->updateEventCapacity($event, $reservedSeats);

            $em->persist($reservation);
            $em->flush();
            $sendmailer = $this->email($user, $mailer);



            $this->addFlash('success', 'La réservation a été effectuée avec succès !');

            return $this->redirectToRoute('app_reservationUser');
        }

        return $this->renderForm("reservation/createReservation.html.twig", [
            "form" => $form,
            // "qrCodeUrl" => $qrCodeUrl,
            "qrcodeDataUri" => $qrcodeDataUri,
        ]);
    }

    #[Route('/user/updateReservation/{id}', name: 'app_updateReservation')]
    public function updateReservation($id, ReservationRepository $re, ManagerRegistry $doctrine, Request $request): Response
    {
        //récupérer la classe à modifier
        $reservations = $re->find($id);
        $form = $this->createForm(ReservationType::class, $reservations);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            //Action de MAJ
            $em = $doctrine->getManager();
            $em->flush();
            return $this->redirectToRoute("app_reservationUser");
        }
        return $this->renderForm("reservation/updateReservation.html.twig", [
            "form" => $form
        ]);
    }


    private function updateEventCapacity(Event $event, $reservedSeats)
    {
        $currentCapacity = $event->getNbPlaceMax();
        $newCapacity = $currentCapacity - $reservedSeats;

        // Vérifier si la nouvelle capacité est supérieure ou égale à zéro
        if ($newCapacity >= 0) {
            $event->setNbPlaceMax($newCapacity);

            $em = $this->getDoctrine()->getManager();
            $em->persist($event);
            $em->flush();
        }
    }



    public function email($user, $mailer)
    {
        // Create a new SMTP transport with the desired configuration
        $dsn = getenv('MAILER_DSN');
        $transport = new Swift_SmtpTransport('smtp.gmail.com', 587, 'tls');
        $transport->setUsername('meriam123.hammi@gmail.com');
        $transport->setPassword('wnevuhcvabtqhhiz');

        $mailer = new Swift_Mailer($transport);

        //BUNDLE MAILER
        $message = (new Swift_Message('Confirmation reservation'))
            ->setFrom('meriam123.hammi@gmail.com')
            ->setTo($user->getEmail())
            ->setBody(" Bonjour,\n \nNous vous confirmons votre réservation pour l'événement");

        //send mail
        $mailer->send($message);
    }
}

templates/reservation/createReservation.html.twig
{% extends 'base.html.twig' %}


{% block title %}Add Reservation{% endblock %}
{% block body %}

<section class="page-header" style="background-image: url({{ asset('/images/backgrounds/page-header-bg-1-1.jpg') }});">
    <div class="container">
        <h2>My reservation</h2>
    </div><!-- /.container -->
</section><!-- /.page-header -->


        <div class="contact-one">
            <div class="container">
                <div class="block-title-two text-center">
                    <p>Reservation</p>
                    <h3>Stay Touch With Tun'art</h3>
                </div><!-- /.block-title-two -->
                <div class="row">
                    <div class="col-lg-4">
                        <div class="contact-one__box">
                            <h3>Opening Hours</h3>
                            <p>Daily: 9.30 AM–6.00 PM <br> Sunday & Holidays: Closed</p>
                        </div><!-- /.contact-one__box -->
                        <div class="contact-one__box">
                            <h3>Contact Info</h3>
                            <p>77408 Satterfield Motorway <br> Suite 469 New Antonetta, BC </p>
                            <p>
                                <a href="mailto:example@muzex.com">example@muzex.com</a> <br> <a href="tel:(617)-495-9400-326">(617) 495-9400-326</a></p>
                        </div><!-- /.contact-one__box -->
                        <div class="contact-one__box">
                            <h3>Social Contact</h3>
                            <div class="contact-one__box-social">
                                <a href="#" class="fab fa-facebook-f"></a>
                                <a href="#" class="fab fa-twitter"></a>
                                <a href="#" class="fab fa-vimeo"></a>
                                <a href="#" class="fab fa-linkedin-in"></a>
                            </div><!-- /.contact-one__box-social -->
                        </div><!-- /.contact-one__box -->
                    </div><!-- /.col-lg-4 -->
                     
                    <div class="col-lg-8">
                 <div class="contact-form-validated contact-one__form" >

 

{% for flashMessage in app.flashes('error') %}
    <div class="alert alert-danger">{{ flashMessage }}</div>
{% endfor %}




                      {{form_start(form,{'attr': {'novalidate': 'novalidate'}} )}}
                            <div class="row">
                                {# <div class="col-lg-6">
                                {{ form_label (form.id_event, "Event") }} 
                                {{ form_widget(form.id_event) }} 
                                 {{ form_errors (form.id_event) }} 
                                </div> #}
                                <div class="col-lg-12">
                                
                               
                                  <div class="col-lg-6">
                                {{ form_label (form.isConfirmed, "Confirmation") }} 
                                {{ form_widget(form.isConfirmed) }} 
                                 {{ form_errors (form.isConfirmed) }} 
                                 </div>
                               
                                 <div class="col-lg-6">
                                {{ form_label (form.nb_place, "Number of places") }} 
                                {{ form_widget(form.nb_place) }} 
                                 {{ form_errors (form.nb_place) }} 

                   


                                
                            </div><!-- /.row -->
                               <div >
                             </div><!-- /.col-lg-12 -->
                                    <div class="col-lg-4 mt-3 d-flex flex-column">
                                    <button class="thm-btn contact-one__btn" >{{ button_label|default('Confirm') }}</button>
                                        <a href="{{ path('app_reservationUser')  }}" class="thm-btn contact-one__btn mt-4" >Retour</a>
                                              
                                </div><!-- /.col-lg-12 -->
                             
                                  <img width="200" class="ml-4 mt-4" src="{{ qrcodeDataUri }}" alt="QR Code">
                                  </div>
                        
                    {{form_end(form)}}

                    
              

                 
                    </div><!-- /.col-lg-8 -->
                   
                </div><!-- /.row --></div>
            </div><!-- /.container -->
        </div><!-- /.contact-one -->

        <div class="contact-map-one">
            <div class="container">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4562.753041141002!2d-118.80123790098536!3d34.152323469614075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80e82469c2162619%3A0xba03efb7998eef6d!2sCostco+Wholesale!5e0!3m2!1sbn!2sbd!4v1562518641290!5m2!1sbn!2sbd" class="google-map__contact" allowfullscreen></iframe>

            </div><!-- /.container -->
        </div><!-- /.contact-map-one -->

        <div class="contact-box-one">
            <div class="container">
                <div class="row high-gutters">
                    <div class="col-lg-6">
                        <div class="contact-box-one__single">
                            <h3>On A Tram</h3>
                            <p>The No. 1 South Melbourne tram goes right past our door. Get off at Stop 18. Any tram down St
                                Kilda Road—jump off at Grant Street, Stop 17 and take a 3-minute walk.</p>
                        </div><!-- /.contact-box-one__single -->
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <div class="contact-box-one__single">
                            <h3>Parking Options</h3>
                            <p>Limited on-street parking is available on Grant Street, Sturt Street and Dodds Streets. Two
                                disabled parking spaces are just outside The Coopers Malthouse entrance on Sturt Street.</p>
                        </div><!-- /.contact-box-one__single -->
                    </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- /.contact-box-one -->

        
{% endblock %}

templates/reservation/index.html.twig
{% extends 'dashboard-base.html.twig' %}


{% block title %}List reservations{% endblock %}
{% block nav %}
                <div class="navbar-nav w-100">
                    <a href="index.html" class="nav-item nav-link active"><i class="fa fa-tachometer-alt me-2"></i>Dashboard</a>
                    <div class="nav-item dropdown">
                        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown"><i class="fa fa-laptop me-2"></i>Gestion events</a>
                        <div class="dropdown-menu bg-transparent border-0">
                            <a href="{{ path('app_addEvent')}}" class="dropdown-item">create event</a>
                            <a href="{{ path('app_addCategorie')}}" class="dropdown-item">create type</a>
                            <a href="{{ path('app_event_categorie')}}" class="dropdown-item">list type</a>
                            <a href="{{ path('app_reservation')}}" class="dropdown-item">list reservation</a>

                        </div>
                    </div>
                    
                </div>
            </nav>
        </div>

        <!-- Sidebar End -->
{% endblock %}

{% block body %}
    <h1>List reservations</h1>


    <table class="table">
        <thead>
            <tr>
                                <th>Id</th>
                                <th>Event</th>
                                <th>Participant</th>
                                <th>Confirmation</th>
                                <th>Number of places</th>
                                <th>Action</th>
                            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                 <td>{{ reservation.id }}</td>
                                <td>{{ reservation.idEvent.title }}</td>
                                <td>{{ reservation.idParticipant.email }}</td>
                                <td>{{ reservation.isConfirmed ? 'Confirmed' : 'Pending' }}</td>
                                <td>{{ reservation.nbPlace }}</td>
                                <td>
                                    <a href="{{ path('app_deleteReservation', {'id': reservation.id}) }}">Delete</a>
                                </td>
                 
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>


    <a href="{{ path('app_event') }}">Back</a>
{% endblock %}

templates/reservation/indexUser.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation index{% endblock %}

{% block body %}
   

<section class="page-header" style="background-image: url({{ asset('images/backgrounds/page-header-bg-1-1.jpg') }});">
    <div class="container">
        <h2>My reservation</h2>
    </div><!-- /.container -->
</section><!-- /.page-header -->

{% if app.session.flashBag.has('danger') %}
        <div class="alert alert-danger">
            {% for message in app.session.flashBag.get('danger') %}
                {{ message }}
            {% endfor %}
        </div>
    {% endif %}
       {% for flashMessage in app.flashes('success') %}
    <div class="alert alert-success">{{ flashMessage }}</div>
{% endfor %}

{% if app.session.flashbag.peek('error') is not empty %}
    <div class="alert alert-danger">
        {% for flash_message in app.session.flashbag.get('error') %}
            {{ flash_message }}
        {% endfor %}
    </div>
{% endif %}


<section class="event-details">

            <div class="container ">
             <a href="{{ path('app_eventFeed') }} "class="mb-4 thm-btn contact-one__btn">back</a>
                <div class="event-details__top">
                  <div class="block-title text-left">
                        <p>Reservations  </p>
                        <h3>My <br> Reservation</h3>
                    </div><!-- /.block-title-two -->
        <div class="row">
        <!-- /.col-lg-4 -->
      

            <div class="col-lg-12">
                <div class="contact-form-validated contact-one__form" >
                    <table class="table">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Event</th>
                                <th>Participant</th>
                                <th>Confirmation</th>
                                <th>Number of places</th>
                                
                                <th>Action</th>
                                
                            </tr>
                        </thead>
                        <tbody>
                       {# {% if qrCodeImage is defined %}
    <img src="{{ qrCodeImage.getDataUri() }}" alt="QR code">
{% endif %} #}


                       {% for reservation in reservations %}
    <tr>
        <td>{{ reservation.id }}</td>
        <td>{{ reservation.idEvent.title }}</td>
        <td>{{ reservation.idParticipant.email }}</td>
        <td>{{ reservation.isConfirmed ? 'Confirmed' : 'Pending' }}</td>
        <td>{{ reservation.nbPlace }}</td>
       

        <td>
            <a href="{{ path('app_deleteReservationUser', {'id': reservation.id}) }}">Delete</a>
        </td>
        <td>
            <a href="{{ path('app_updateReservation', {'id': reservation.id}) }}">Edit</a>
        </td>
        
    </tr>
{% else %}
    <tr>
        <td colspan="6">no records found</td>
    </tr>
{% endfor %}

                        </tbody>
                    </table>
                </div><!-- /.contact-form-validated -->
            </div><!-- /.col-lg-8 -->
        </div><!-- /.row -->
    </div><!-- /.container -->
</div><!-- /.contact-one -->
{% endblock %}

templates/reservation/updateReservation.html.twig
{% extends 'base.html.twig' %}


{% block title %}Edit Reservation{% endblock %}
{% block body %}

section class="page-header" style="background-image:  url({{asset('images/backgrounds/page-header-bg-1-1.jpg')}});">

            <div class="container">
                <h2>Edit reservation</h2>
            </div><!-- /.container -->
        </section><!-- /.page-header -->


        <div class="contact-one">
            <div class="container">
                <div class="block-title-two text-center">
                    <p>Contact</p>
                    <h3>Stay Touch With Tun'art</h3>
                </div><!-- /.block-title-two -->
                <div class="row">
                    <div class="col-lg-4">
                        <div class="contact-one__box">
                            <h3>Opening Hours</h3>
                            <p>Daily: 9.30 AM–6.00 PM <br> Sunday & Holidays: Closed</p>
                        </div><!-- /.contact-one__box -->
                        <div class="contact-one__box">
                            <h3>Contact Info</h3>
                            <p>77408 Satterfield Motorway <br> Suite 469 New Antonetta, BC </p>
                            <p>
                                <a href="mailto:example@muzex.com">example@muzex.com</a> <br> <a href="tel:(617)-495-9400-326">(617) 495-9400-326</a></p>
                        </div><!-- /.contact-one__box -->
                        <div class="contact-one__box">
                            <h3>Social Contact</h3>
                            <div class="contact-one__box-social">
                                <a href="#" class="fab fa-facebook-f"></a>
                                <a href="#" class="fab fa-twitter"></a>
                                <a href="#" class="fab fa-vimeo"></a>
                                <a href="#" class="fab fa-linkedin-in"></a>
                            </div><!-- /.contact-one__box-social -->
                        </div><!-- /.contact-one__box -->
                    </div><!-- /.col-lg-4 -->
                     
                    <div class="col-lg-8">
                 <div class="contact-form-validated contact-one__form" >

 

                      {{form_start(form,{'attr': {'novalidate': 'novalidate'}} )}}
                            <div class="row">
                           
                                <div class="col-lg-12">
                            
                               
                                  <div class="col-lg-6">
                                {{ form_label (form.isConfirmed, "Confirmation") }} 
                                {{ form_widget(form.isConfirmed) }} 
                                 {{ form_errors (form.isConfirmed) }} 
                                 </div>
                               
                                 <div class="col-lg-6">
                                {{ form_label (form.nb_place, "Number of places") }} 
                                {{ form_widget(form.nb_place) }} 
                                 {{ form_errors (form.nb_place) }} 
                                 </div>
                                 

                                
                            </div><!-- /.row -->
                             </div><!-- /.col-lg-12 -->
                                    <div class="col-lg-12 mt-3">
                                    <button class="thm-btn contact-one__btn" >{{ button_label|default('Confirm') }}</button>
                                </div><!-- /.col-lg-12 -->
                                <a href="{{ path('app_reservation') }} " class="thm-btn contact-one__btn">Retour</a>

                    {{form_end(form)}}
                 
                    </div><!-- /.col-lg-8 -->
                   
                </div><!-- /.row --></div>
            </div><!-- /.container -->
        </div><!-- /.contact-one -->

        <div class="contact-map-one">
            <div class="container">
                <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4562.753041141002!2d-118.80123790098536!3d34.152323469614075!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80e82469c2162619%3A0xba03efb7998eef6d!2sCostco+Wholesale!5e0!3m2!1sbn!2sbd!4v1562518641290!5m2!1sbn!2sbd" class="google-map__contact" allowfullscreen></iframe>

            </div><!-- /.container -->
        </div><!-- /.contact-map-one -->

        <div class="contact-box-one">
            <div class="container">
                <div class="row high-gutters">
                    <div class="col-lg-6">
                        <div class="contact-box-one__single">
                            <h3>On A Tram</h3>
                            <p>The No. 1 South Melbourne tram goes right past our door. Get off at Stop 18. Any tram down St
                                Kilda Road—jump off at Grant Street, Stop 17 and take a 3-minute walk.</p>
                        </div><!-- /.contact-box-one__single -->
                    </div><!-- /.col-lg-6 -->
                    <div class="col-lg-6">
                        <div class="contact-box-one__single">
                            <h3>Parking Options</h3>
                            <p>Limited on-street parking is available on Grant Street, Sturt Street and Dodds Streets. Two
                                disabled parking spaces are just outside The Coopers Malthouse entrance on Sturt Street.</p>
                        </div><!-- /.contact-box-one__single -->
                    </div><!-- /.col-lg-6 -->
                </div><!-- /.row -->
            </div><!-- /.container -->
        </div><!-- /.contact-box-one -->

        
{% endblock %}